pruebas_index:
    path: /pruebas/{lang}/{name}/{age}
    defaults: { _controller: AppBundle:Pruebas:index, lang:es, name:Gemerson, age:18 }
    methods: [GET, POST] 
    requirements:
        name: \w+
        age: \d+
        lang: es|en|fr
